### ISSUE TITLE
Text id?

### ISSUE THREAD

**Issue by mlohbihler** [rogierslag/pg-migration#3]
Hi Rogier,

I like this package. Simple and to the point! Is there any reason why you chose bigint instead of text for dbchangelog.id? Text would allow more descriptive filenames. I was going to create a PR, but wanted to check with you first.

Thanks,
Matthew

**Comment by rogierslag** [comment]
In this case its because I execute all the sql in the order the files. Sorting by date at least makes it stable. It would definitely possible to change this to text, as long as you ensure the file names are still sorted.

A system like RoR does by prefixing the descriptive name with the text would be sufficient for that I think

**Comment by mlohbihler** [comment]
Thanks Rogier. I noticed the use of bigint because i was using e.g. '2017-09-15-01' as my filename, which didn't work so well. I think if the filenames were just sorted before iterating that would provide the same effect as before. I agree that there is still an onus on developers to provide a suitably sortable name for their files.

But since my first message i had another problem. Currently you are running all of the updates/migrations simultaneously. This is a problem in my case because i had "create table"s in one file and "insert into"s in the second. Although the files would be run in the proper order, the commands within would not, and the process would error out. I have a change that runs all of the promises serially. I'll create a PR so you can have a look.
